config/routes.rb
Theodinproject::Application.routes.draw do
devise_for :users, 
  :controllers => { :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks",
    :confirmations => "confirmations" }
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', :method => :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  root :to => 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'scheduler' => redirect('/courses')
  post 'thank_you' => 'static_pages#send_feedback'
  post 'suggestion' => 'static_pages#suggestion'
  get 'students' => 'users#index'
  get 'about' => "static_pages#about"
  get 'faq' => "static_pages#faq"
  get 'contact' => "static_pages#contact"
  get 'getting_involved' => "static_pages#getting_involved"
  get 'contributing' => "static_pages#contributing"
  get 'studygroup' => redirect('/studygroups')
  get 'legal' => "static_pages#legal"
  get 'cla' => "static_pages#cla"
  get 'tou' => "static_pages#tou"
  get 'press' => redirect('https://docs.google.com/document/d/1FmjfYvOsQ-syoOCzuvPXv96TCxeJAT9m-Wl7trgNZcE/pub')
  get 'studygroups' => "static_pages#studygroups"

  #failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'


  resources :cal_events

  # This is being hidden until needed (it was needed by the scheduler
  # but that got killed but will still be useful later)
  # resource :user_pref, :only => [:edit, :update]

  resources :users, :only => [:show, :index, :edit, :update] do
    resource :contact, :only => [:new, :create]
  end

  resources :splash_emails, :only => [:create]

  resource :forum, :only => [:show]

  post 'lesson_completions' => 'lesson_completions#create'
  delete 'lesson_completions/:lesson_id' => 'lesson_completions#destroy', :as => "lesson_completion"

  # Sitemap
  get "sitemap" => "sitemap#index", :defaults => { :format => "xml" }

  # ***** COURSES AND LESSONS ROUTES *****

  get 'curriculum' => redirect('/courses')
  get 'courses' => 'courses#index'

  # Explicitly redirect deprecated routes (301)
  get 'courses/:course_name' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons' => redirect('/%{course_name}')
  get 'courses/:course_name/lessons/:lesson_name' => redirect('/%{course_name}/%{lesson_name}')

  # Match all undefined routes as courses and/or lessons
  get ':course_name' => 'lessons#index', :as => "course"
  get ':course_name' => 'lessons#index', :as => "lessons"
  get ':course_name/:lesson_name' => 'lessons#show', :as => "lesson"


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Make sure we get the preference built after the user saves
  after_create :build_preferences

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :about, :github, :facebook, :twitter, :linkedin, :skype, :screenhero, :google_plus, :legal_agreement, :provider, :uid

  validates_uniqueness_of :username,:email
  validates_presence_of :legal_agreement, :message => "Don't forget the legal stuff!", :on => :create
  validates :username, :length => { :in => 4..20 }

  # basic associations
  has_many :cal_events, :foreign_key => :creator_id
  has_one :user_pref
  # associates the user to the content he'd like to pair on
  has_many :content_activations, :dependent => :destroy
  has_many :content_buckets, :through => :content_activations
  # associates the user with the lessons he's completed so far
  has_many :lesson_completions, :foreign_key => :student_id
  has_many :completed_lessons, :through => :lesson_completions, :source => :lesson

  # Return all users sorted by who has completed a lesson
  # most recently
  # NOTE: The order clause will break if not on Postgres because
  # NULLS LAST is PG-specific apparently
  def self.by_latest_completion
    User.where.not(:last_sign_in_at => nil)
        .joins("LEFT OUTER JOIN lesson_completions ON lesson_completions.student_id = users.id")
        .select("max(lesson_completions.created_at) as latest_completion_date, users.*")
        .group("users.id")
        .order("latest_completion_date desc NULLS LAST")
  end

  def completed_lesson?(lesson)
    self.completed_lessons.include?(lesson)
  end

  def latest_completed_lesson
    lc = self.latest_lesson_completion
    Lesson.find(lc.lesson_id) unless lc.nil?
  end

  def latest_lesson_completion
    self.lesson_completions.order(:created_at => :desc).first
  end

  include Authentication::ActiveRecordHelpers #check in domain/authentication/active_record_helpers.rb

  # Create a completely new user from our auth package
  # Returns that user
  def self.from_omniauth(auth)
    #puts "\n\n\n\n\n\n\n #{auth} \n\n\n\n\n\n\n\n"
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.username = auth['info']['nickname']
      user.email = auth['info']['email']
    end
  end

  # Assumes an existing user does not have omniauth
  # Adds auth, saves, and returns the user
  def add_omniauth(auth)
    self.provider ||= auth['provider']
    self.uid ||= auth['uid']
    self.save
    self
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  # Overwrite Devise method to allow users who registered before confirmation was required
  # to continue using the site without being forced to confirm their email.
  def active_for_authentication?
    super && (!confirmation_required? || confirmed? || confirmation_period_valid?) || reg_before_conf?
  end

  # Overwrite Devise method to send welcome email to new users with confirmation token
  # Users who registered before confirmation was required receive normal confirmation email
  def send_confirmation_instructions
    unless @raw_confirmation_token
      generate_confirmation_token!
    end
    if self.reg_before_conf == true
      opts = pending_reconfirmation? ? { to: unconfirmed_email } : { }
      send_devise_notification(:confirmation_instructions, @raw_confirmation_token, opts)
    else  # new user
      send_welcome_email(@raw_confirmation_token)
    end
  end


  protected

    def build_preferences
      self.create_user_pref
    end

    def send_welcome_email(token)
      begin
        @token = token
        UserMailer.send_welcome_email_to(self, token).deliver!
      rescue Exception => e
        puts "Error sending welcome email!"
        puts e.message
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_current_user, :only => [:edit, :update]

  def show
    @user = User.find_by_id(params[:id])
    if @user
    else
      flash[:error] = "There was no user by that name"
      redirect_to :back
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user
      @edit = true
      render :show
    else
      flash[:error] = "There was no user by that name"
      redirect_to :back
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user
      @user.update_attributes(params[:user])
      flash[:success] = "Your profile was updated successfully"
      redirect_to @user
    end
  end

  def index
    # Grab students and order by most recent lesson completion
    # @users = User.where.not(:last_sign_in_at => nil).order("last_sign_in_at desc").paginate(:page => params[:page], :per_page => 15)
    @users = User.by_latest_completion.paginate(:page => params[:page], :per_page => 15)
  end

  def send_confirmation_link
    current_user.send_confirmation_instructions
    flash[:notice] = "Confirmation instructions have been sent to your email address!"
    redirect_to request.referer
  end

  protected

  def check_current_user
    user = User.find_by_id(params[:id]) || bad_request
    if user
      unless current_user == user
        # puts "**** redirecting because you aren't this user! ****"
        logger.warn "**** redirecting because you (#{current_user.username}) aren't this user! ****"
        redirect_to user
      end
    else
      render "/400.html", :status => 400 # bad request
    end
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :legal_agreement)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, size)
    gravatar_hash = Digest::MD5.hexdigest(user.email.strip.downcase)
    default_url = "http://www.gravatar.com/avatar/436053b3e050d4156773bc04cfb167fe?s=#{size}"
    # #{root_url}assets/odin_head_silhouette_2_pale.gif
    gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_hash}?s=#{size}&d=#{default_url}"
  end

  def twitter_url(user)
    url = ""
    if user.twitter
      if user.twitter[0] == "@"
        url = "http://www.twitter.com/#{user.twitter[1..-1]}"
      else
        url = "http://www.twitter.com/#{user.twitter}"
      end
    else
      url
    end
  end 
end

app/views/users/_user.html.erb
<div class="row student">
  <div class="student-pic">
    <a href="<%= user_path(user) %>">
      <img src="<%= gravatar_url(user, 100) %>" title="<%= user.username %>" class="student-mini-pic">
    </a>
  </div>
  <div class="student-info">
    <h3><%= link_to "#{user.username}", user %></h3>
    <% lesson = user.latest_completed_lesson %>
    <% if lesson %>
      <em>
        Completed 
        "<%= link_to "#{lesson.course.title}: #{lesson.title}", lesson_path(lesson.course.title_url, lesson.title_url) %>" <%= distance_of_time_in_words(Time.now - user.latest_lesson_completion.created_at) %> ago
      </em>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="span8 offset2">
      <h2>Students</h2>
      <div id="students-list">
        <% @users.each do |user| %>
          <%= render user %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render :partial => "shared/pagination", :locals => {:collection => @users }%>

app/views/users/show.html.erb
<div id="profile-page" class="container">
  <% if @edit %>
    <form accept-charset="UTF-8" id="edit-user" method="post" action="/users/<%= @user.id %>">
      <input name="_method" type="hidden" value="put">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  <% end %>

  <div class="row">

    <div class="span3 offset1">
      <div class="profile-photo-container">
        <img src="<%= gravatar_url(@user, 270) %>">
        <% if @edit %>
          <%= link_to "Edit your Gravatar image", "https://en.gravatar.com/site/login", :class => "edit-gravatar", :target => "_blank", :title => "Go to Gravatar.com to edit your profile image.  Gravatar lets you change your profile photo in just one place (their site) and then it's available to any other site that links to it (which is a lot of them). That way, when you want to change your photo later, you don't need to track it down on a dozen different websites. Cool!" %>
        <% end %>
      </div>
    </div>

    <div class="span6">
      <h2 class="profile-headline"><%= @user.username %>'s Profile</h2>
      <% if @user == current_user %>
        <% if @edit %>
          <input type="submit" class="btn btn-medium btn-primary edit-profile" value="Update" >
          <%= link_to "Cancel", @user, :class => "edit-profile" %>
        <% else %>
          <a href="<%= edit_user_path(current_user) %>"><button class='edit-profile btn btn-medium'>Edit Profile</button></a>
        <% end %>
      <% end %>
      <% if @user == current_user && @user.provider.nil? %>
        <%- User.omniauth_providers.each do |provider| %>
          <%= link_to "<i class=\"fa fa-#{provider} providers-button\"></i>Link your #{provider.to_s.titleize} account".html_safe, omniauth_authorize_path(:user, :github), id: 'github-link', class: 'btn btn-social btn-large btn-lg btn-github' %><br />
        <% end -%>
      <% end %>
      <h3>About</h3>
      <div class="profile-about">
        <% if @edit %>
          <textarea id="user_about" name="user[about]" cols="70" rows="8" placeholder="Tell us about yourself!"><%= @user.about %></textarea>
        <% else %>
          <p>
            <%= @user.about %>
          </p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span3 offset1">
      <h3 class="contact-me">Contact Info</h3>
      <% if @user != current_user %>
        <a href="<%= new_user_contact_path(@user) %>">
          <button class="contact-user-button btn btn-primary">
            Email Me!
          </button>
        </a>
      <% end %>
      <div class="profile-contact-links">
        <% if @edit %>
          <ul>
            <li><input type="text" id="user_skype" name="user[skype]" size="50" placeholder="Skype username..." value="<%= @user.skype %>"></li>
            <li><input type="text" id="user_screenhero" name="user[screenhero]" size="50" placeholder="ScreenHero username..." value="<%= @user.screenhero %>"></li>
            <li><input type="text" id="user_google_plus" name="user[google_plus]" size="50" placeholder="Google Plus username..." value="<%= @user.google_plus %>"></li>
            <li><hr></li>
            <li><input type="text" id="user_github" name="user[github]" size="50" placeholder="Github username..." value="<%= @user.github %>"></li>
            <li><input type="text" id="user_twitter" name="user[twitter]" size="50" placeholder="Twitter handle..." value="<%= @user.twitter %>"></li>
            <li><input type="text" id="user_facebook" name="user[facebook]" size="50" placeholder="URL for your Facebook profile..." value="<%= @user.facebook %>"></li>
            <li><input type="text" id="user_linkedin" name="user[linkedin]" size="50" placeholder="URL for your LinkedIn profile..." value="<%= @user.linkedin %>"></li>
          </ul>

        <% else %>

          <ul>
            <li>Skype: <%= @user.skype %></li>
            <li>ScreenHero: <%= @user.screenhero %></li>
            <li>Google Plus: <%= @user.google_plus %></li>
            <li><hr></li>
            <li>Github: <a href="http://www.github.com/<%= @user.github %>"><%= @user.github %></a></li>
            <li>Twitter: <a href="<%= twitter_url(@user)%>"><%= @user.twitter %></a></li>
            <li>Facebook: <a href="<%= @user.facebook %>"><%= @user.facebook %></a></li>
            <li>LinkedIn: <a href="<%= @user.linkedin %>"><%= @user.linkedin %></a></li>
          </ul>
        <% end %>
      </div>
    </div>

    <div class="span6">
      <div class="profile-projects">
        <h3>Completed Lessons</h3>
        <ul>
          <% @user.completed_lessons.each do |lesson| %>
            <li><%= link_to("#{lesson.course.title}:  #{lesson.title}", lesson_path(lesson.course.title_url, lesson.title_url)) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <% if @edit %>
      </form>
    <% end %>

  </div>

</div>